import type { Metadata } from "next";
import {
  NextIntlClientProvider,
  useMessages,
} from "next-intl";

import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { useAppStore } from "@/store/appStore";

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function LocalLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
          {children}
      </html>
    </NextIntlClientProvider>
  );
}
