import type { Metadata } from "next";
import {
  NextIntlClientProvider,
  useMessages,
} from "next-intl";

import "../globals.css";

export const metadata: Metadata = {
  title: "Nexus",
  description: "Generated by create next app",
};

export default function LocalLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = useMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale} className="">
        <body className="flex flex-col items-center h-screen">
          {children}
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
